name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Github repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: example.tex
      - name: Release LaTeX dopcument to Github pages
        run: |
          git config --global user.name 'sws-bot'
          git config --global user.email 'iamabotanddonothaveavaliudemail@address.org'
          git pull
          git checkout gh-pages
          git commit example.pdf -m "automated push"
          git push --set-upstream origin gh-pages
