name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Github repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: example.tex
      - name: Release LaTeX dopcument to Github pages
        uses: softprops/action-gh-release@v1
        with:
          files: example.pdf
